-- Run this in Supabase SQL Editor.
create table if not exists public.site_analytics (
  id bigint primary key,
  visits bigint not null default 0,
  "contactClicks" bigint not null default 0,
  "contactForms" bigint not null default 0,
  "pageViews" bigint not null default 0,
  "mobileVisits" bigint not null default 0,
  "desktopVisits" bigint not null default 0,
  "profileClicks" jsonb not null default '{}'::jsonb,
  events jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  organization text,
  email text not null,
  profile text,
  message text,
  created_at timestamptz not null default now(),
  constraint contacts_name_length check (char_length(name) between 1 and 120),
  constraint contacts_email_length check (char_length(email) between 3 and 254),
  constraint contacts_message_length check (message is null or char_length(message) <= 5000)
);

create table if not exists public.site_config (
  id bigint primary key,
  config jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_roles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.site_analytics enable row level security;
alter table public.contacts enable row level security;
alter table public.site_config enable row level security;
alter table public.admin_roles enable row level security;

-- Make this script safe to re-run during deployment.
drop policy if exists "public can upsert analytics" on public.site_analytics;
drop policy if exists "public can update analytics" on public.site_analytics;
drop policy if exists "public can create contacts" on public.contacts;
drop policy if exists "public can upsert site config" on public.site_config;
drop policy if exists "public can update site config" on public.site_config;
drop policy if exists "admins can read analytics" on public.site_analytics;
drop policy if exists "admins can read contacts" on public.contacts;
drop policy if exists "admins can read site config" on public.site_config;
drop policy if exists "authenticated can upsert analytics" on public.site_analytics;
drop policy if exists "authenticated can update analytics" on public.site_analytics;
drop policy if exists "authenticated can upsert site config" on public.site_config;
drop policy if exists "authenticated can update site config" on public.site_config;
drop policy if exists "admins can read own role" on public.admin_roles;

-- Public users can submit contacts. Aggregate/configuration changes require Auth.
create policy "public can create contacts" on public.contacts for insert with check (true);
create policy "authenticated can upsert analytics" on public.site_analytics for insert to authenticated with check (exists (select 1 from public.admin_roles where user_id = auth.uid()));
create policy "authenticated can update analytics" on public.site_analytics for update to authenticated using (exists (select 1 from public.admin_roles where user_id = auth.uid())) with check (exists (select 1 from public.admin_roles where user_id = auth.uid()));
create policy "authenticated can upsert site config" on public.site_config for insert to authenticated with check (exists (select 1 from public.admin_roles where user_id = auth.uid()));
create policy "authenticated can update site config" on public.site_config for update to authenticated using (exists (select 1 from public.admin_roles where user_id = auth.uid())) with check (exists (select 1 from public.admin_roles where user_id = auth.uid()));
create policy "admins can read own role" on public.admin_roles for select to authenticated using (user_id = auth.uid());

-- Keep reads restricted to authenticated administrators.
create policy "admins can read analytics" on public.site_analytics for select to authenticated using (exists (select 1 from public.admin_roles where user_id = auth.uid()));
create policy "admins can read contacts" on public.contacts for select to authenticated using (exists (select 1 from public.admin_roles where user_id = auth.uid()));
create policy "admins can read site config" on public.site_config for select to authenticated using (exists (select 1 from public.admin_roles where user_id = auth.uid()));
